apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
  namespace: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      securityContext:
        runAsUser: 7474
        runAsGroup: 7474
        fsGroup: 7474
      initContainers:
        - name: init-chown-data
          image: busybox:1.36
          command: ["sh", "-c", "chown -R 7474:7474 /data"]
          securityContext:
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
      containers:
        - name: neo4j
          image: neo4j:5.8.0
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              valueFrom:
                secretKeyRef:
                  name: neo4j-secret
                  key: NEO4J_AUTH
            - name: NEO4J_PLUGINS
              value: '["apoc"]'
            - name: NEO4J_apoc_import_file_use__neo4j__config
              value: "true"
            - name: NEO4J_apoc_import_file_enabled
              value: "true"
            - name: NEO4J_apoc_export_file_enabled
              value: "true"
            - name: NEO4J_dbms_security_procedures_unrestricted
              value: "apoc.*"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "2G"
            - name: NEO4J_dbms_memory_pagecache_size
              value: "2G"
            - name: NEO4J_server_config_strict__validation_enabled
              value: "false"            
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
            - name: neo4j-plugins
              mountPath: /plugins
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-pvc
        - name: neo4j-plugins
          hostPath:
            path: /neo4j-plugins
